### ISSUE TITLE
Error 401 when POSTing from interactive job

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/rodan-client#107] opened 2016-05-06 19:23 UTC
Sometimes, our interactive jobs become unable to POST back to the server.  Each POST returns Error 401.

I have isolated this problem to `InteractiveWorkingView._authenticate()`.  This is the `if` statement from the Rodan server which is throwing the error:

```
if runjob.working_user_token != uuid.UUID(working_user_token):
            raise CustomAPIException({'message': 'Permission denied'},  status=status.HTTP_401_UNAUTHORIZED)
```

It seems that there is a mismatch between the `runjob.working_user_token` and the `working_user_token` from the URL of the interactive job.

I suspect that the Rodan Client isn't updating the working user token that it uses to generate the interactive job URL.

I have been unable to replicate the bug reliably.

**Comment by AFFogarty** [comment] 2016-05-06 19:57
After more investigation, it seems that the runjob's `working_user_token` keeps getting changed because the client continues hitting the `/interactive/----uuid----/acquire/` enpoint after the Interactive Job has already been opened!

**Comment by AFFogarty** [comment] 2016-05-06 20:08
Ok, I found out what the bug is.

When you click on the "WAITING FOR INPUT" interactive job and it starts to open, the Rodan client stops POSTing to the `acquire` endpoint for a few seconds.

This causes the `runjob.working_user_expiry` to time out!  The next time `acquire` is hit, the Rodan server generates a new `working_user_token` and the currently open interactive job window becomes invalid!

**Comment by mrbannon** [comment] 2016-05-06 20:47
That makes sense. It needs to keep acquiring the job. This should be simple
to solve. Tx.

**Comment by mrbannon** [comment] 2016-05-09 17:52
I wasn't able to recreate the issue, but I DID find another issue (not reacquiring properly). Also, the WorkflowRun view not updates RunJobs and Resource lists. 

I'm going to close this for now. If it happens again, please reopen.

**Comment by AFFogarty** [comment] 2016-05-10 19:19
Ok it happened again.

**Comment by mrbannon** [comment] 2016-05-10 19:26
Balls!!!!

**Comment by AFFogarty** [comment] 2016-05-10 19:46
Yeah, it seems that the Rodan client freezes when the Interactive Classifier window freezes.  This freeze is what causes the token to time-out.

**Comment by mrbannon** [comment] 2016-05-10 19:49
Please make a note as to what view you are in when launching the job. (E.g.
workflow run view our runjobs view)

**Comment by AFFogarty** [comment] 2016-05-10 19:50
It happens in both.

**Comment by mrbannon** [comment] 2016-05-11 13:57
I THINK I might know what the issue is, and why I'm not getting it.

Either grab me so we can take a look OR check the following:

- In the Javascript log, are you seeing "EVENT__SERVER_DATE_UPDATED"? It should be firing at regular intervals...probably every 5-10 seconds. (FYI, this event is sent out every time the client gets a response from the server...ANY kind of response. This makes sure that the client knows the server time so it can reacquire interactive jobs.)

- In the Rodan server settings (Rodan/rodan/settings.py), is the 'Date' header being exposed?

**Comment by mrbannon** [comment] 2016-05-11 17:59
For now, the best solution is setting RODAN_RUNJOB_WORKING_USER_EXPIRY_SECONDS in the Rodan settings to a higher number, like 60. I'll have to look at this some more.

**Comment by AFFogarty** [comment] 2016-05-25 18:02
So I've basically solved this issue in https://github.com/DDMAL/Interactive-Classifier/commit/3744a23b7d9f4d598adbad950fb1b8f9bfe94ad9.

I have created a new `Authenticator` class in the interactive job JS code.  The authenticator polls the server `/acquire` endpoint to maintain the `runjob.working_user_expiry` token.  If the token expires, the `Authenticator` will acquire a new token and save the new token `working_url`.

This way, the Interactive Job (which is in a different window than the Rodan Client) is not dependent upon the Rodan client to maintain the token.  So, if the user closes the Rodan Client or the Client crashes, the Interactive Job will not be invalidated.

**Comment by mrbannon** [comment] 2016-06-10 20:21
Since @AFFogarty wrote that great class, I'm closing this. I reference his class in the Rodan Interactive RunJob API wiki (not in Rodan Client).

**Closed by mrbannon** 2016-06-10 20:21 UTC
Labels: Priority: MAJOR, Type: FIX
